# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7edd87f22f3d375d7070f3e65e59b5ba69e2af66c6b20b8df7f48482d405fe3460728a1bf548957a31ebb764169469d5248ff15558b35a04b7ab34f6a71335a6

test:
  secret_key_base: 4f5ee9787378ecaca5fead47367e28e78dd36848cb8fded70dc320bbd5c16f99f3d469828b638e710bef19598210e4baf22e20cc4955da572300e61ef4a03e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
